### ISSUE TITLE
Add ability to refactor into a multi-resource declaration

### ISSUE THREAD

**Issue by genebean** [puppetlabs/puppet-vscode#464]
**Summary of the new feature**

I would like to be able to select a group of resources of the same type and have VS Code refactor them into a multi-resource declaration. Simply doing the reformatting would be enough but a streatch goal would be to have it populate the default section by deduplicating the declared parameters.

For example: 

Individual resources:

```puppet
file { $haproxy_cert_dir:
  ensure => directory,
  mode   => '0755',
  notify => Haproxy::Service['haproxy'],
}

file { $puppet_ca_file:
  ensure => file,
  mode   => '0644',
  source => '/etc/puppetlabs/puppet/ssl/certs/ca.pem',
  notify => Haproxy::Service['haproxy'],
}

file { $puppet_crl_file:
  ensure => file,
  mode   => '0644',
  source => '/etc/puppetlabs/puppet/ssl/crl.pem',
  notify => Haproxy::Service['haproxy'],
}
```

A multi-resource declaration:

```puppet
file {
  default:
    ensure => file,
    mode   => '0644',
    notify => Haproxy::Service['haproxy'],
  ;
  $haproxy_cert_dir:
    ensure => directory,
    mode   => '0755',
  ;
  $puppet_ca_file:
    source => '/etc/puppetlabs/puppet/ssl/certs/ca.pem',
  ;
  $puppet_crl_file:
    source => '/etc/puppetlabs/puppet/ssl/crl.pem',
  ;
}
```

**Comment by genebean** [comment]
I'd still very much like to see this done.

**Comment by jpogran** [comment]
I'm going to convert this to a Github discussion so that we can gain some consensus on the implementation before committing to a feature ticket.
