### ISSUE TITLE
Change build script githubref to Github standard format

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#583]
Currently we represent the config for the editor services as:

```
"editorServices": {
  "githubuser": "glennsarti",
  "githubrepo": "puppet-editor-services",
  "githubref": "spike-rearch-langserver"
},
```

I never remember the format or the names. How about we use the github format:

```json
"editorServices": {
  "githubrepo": "puppet-editor-services",
  "githubref": "glennsarti:spike-rearch-langserver"
},
```

This way, we can click the copy button in the PR for the user:branch and then paste in without having to edit more text.

**Comment by glennsarti** [comment]
Sure.
