### ISSUE TITLE
The schema for puppet's metadata.json is applied on any file named metadata.json

### ISSUE THREAD

**Issue by Zezombye** [puppetlabs/puppet-vscode#615]
### What Versions are you running?

OS Version: Debian 10
VSCode Version: 1.43.1
Puppet Extension Version: 0.24.0
PDK Version: /

### What You Are Seeing?

The schema for puppet's metadata.json is applied on any file named metadata.json, making it underline basically the whole file in yellow.

![](https://i.imgur.com/arKSUuT.png)

### What is Expected?

Either:
- The extension only applies the schema if it detects it is in a puppet module, by the surrounding folder names, though that is hacky.
- The extension does not apply the schema, or does not attempt to validate the metadata.json file.
- The extension gives a way to disable schema check for metadata.json files (and should be disabled by default).
- The extension adds a new language "puppet-metadata-json" that can be, on behalf of the user, applied to these files.

### How Did You Get This To Happen? (Steps to Reproduce)

Create any file named metadata.json, and put any valid JSON in it.

### Output Log

/

**Comment by jpogran** [comment]
Thanks for the bug report. You're correct this is not ideal.

VS Code applies json schema's based on filenames, and activates if the supplied conditions are met.  I'll have to figure out some way of doing this differently

**Comment by jpogran** [comment]
Hi @Zezombye ,

Apologies, but this won't be fixed for the next release which is coming this Friday. The reason this is happening is that VS Code provides one configuration point for json valiadtion: https://github.com/lingua-pupuli/puppet-vscode/blob/master/package.json#L109. It is meant to apply that validation to any file that matches the name provided. Our extension activates if any of the following events occur: https://github.com/lingua-pupuli/puppet-vscode/blob/master/package.json#L62-L78. This means that if your editor is open and the current working directory matches any of those files, or if you ran any of those commands, it will validate any `metadata.json` file with our schema.

While we decide how to handle this in a future release, you can work around this behavior by [temporarily disabling the extension in your workspace](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension). This will prevent our validator from running on your json document.

**Comment by Zezombye** [comment]
Still important

**Comment by jpogran** [comment]
Hi @Zezombye, I am sorry to say that we have to close this issue. VS Code does not provide us a way to prevent this from happening if the extension is activated.

The workaround is to either temporarily disable the extension in your workspace or to open different projects with other metadata.json files in VS Code windows that have not had the Puppet extension already activated.
