### ISSUE TITLE
Request: Highlight Puppet Lint configuration

### ISSUE THREAD

**Issue by mcandre** [puppetlabs/puppet-vscode#624]
**Summary of the new feature**

* `.puppet-lint.rc` (shell script)

---
**As a** user

**I would like to** automatically format my puppet lint config files

**so that I** don't have to manually adjust the file language.

**Comment by jpogran** [comment]
The Puppet Extension does not control what language is associated with rc files, VS Code does. If you want to set VS Code to use a specific language for certain file extensions, you can use the "files.associations" setting. For example, the following sets `rc` files to use the `Shell language`.

```
"files.associations": {
   "*.rc": "shellscript",
}
```

**Comment by jpogran** [comment]
@mcandre does the above comment solve your request?
