### ISSUE TITLE
boolean default task value marked as "Incorrect type"

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppet-vscode#625]
### What Versions are you running?

OS Version: macOS 10.15.4
VSCode Version: 1.44.2
Puppet Extension Version: 0.25.2
PDK Version: N/A
Puppet version: 5.5.19
Bolt version: 2.5.0

### What You Are Seeing?
in task metadata file Boolean parameter with default value is treated as an error
```
        "offline": {
            "type": "Boolean",
            "default": false
        }
```

message shows:
```
Incorrect type. Expected "string".
```

### What is Expected?

Extension should recognize default boolean value as correct syntax

**Comment by jpogran** [comment]
Our JSON validation comes from the JSON schema the Bolt team maintains at https://forgeapi.puppet.com/schemas/task.json. Looking at what is there right now, it seems like they haven't updated their schema to allow booleans:

```json
"definitions": {
    "parameterName": {
      "description": "Valid names for parameter keys",
      "type": "string",
      "pattern": "^[a-z][a-z0-9_]*$"
    },
    "paramsObject": {
      "type": "object",
      "description": "An object with restricted keys and enumData support",
      "propertyNames": {"$ref": "#/definitions/parameterName"},
      "additionalProperties": {
        "type": "object",
        "description": "Extend Normal JSON schema to require an object and describe 'enumData' to map enum values to descriptions",
        "properties": {
          "description": {
            "description": "A description of the parameter",
            "type": "string"
          },
          "type": {
            "description": "A puppet type string that describes a data type that will match the parameter value",
            "type": "string"
          },
          "sensitive": {
            "description": "Whether the task runner should treat the parameter value as sensitive",
            "type": "boolean",
            "default": false
          },
          "default": {
            "description": "The default value to pass to the task implementation if the parameter isn't provided",
            "type": "string"
          }
        }
      }
    }
  }
```

**Comment by adreyer** [comment]
I don't know how forge get's updated but the source of truth is here. I'll put up a PR to update it.

https://github.com/puppetlabs/puppet-specifications/blob/master/tasks/task.json#L111

**Comment by adreyer** [comment]
@vchepkov it looks like forge is updated can you verify that vscode works?

**Comment by vchepkov** [comment]
It works now, thanks, fantastic turnaround
