### ISSUE TITLE
Feature request: Support for eyaml

### ISSUE THREAD

**Issue by rogermartensson** [puppetlabs/puppet-vscode#626]
Since EYaml is such an integral part of puppet it would be nice to have this functionality included to the extension.

There is already an extension with some rudimentary functionality in the repository but it looks abandoned.

Features I think would be nice to have is:
- encrypt/decrypt marked strings to strings/blocks (duh!)
- Support for multiple keys (eg. difference in test/production using same control-repo)
- Store private key in an encrypted/password protected state (for higher security)
- encrypt/decrypt files

**Comment by jpogran** [comment]
Thanks for the feature suggestion. This is something we've thought of doing in the past, thanks for adding additional support for it. We won't get to this in this upcoming release, but will update this issue as it comes closes to being planned

**Comment by jpogran** [comment]
This is referencing https://github.com/brandontosch/vscode-hiera-eyaml

**Comment by jpogran** [comment]
I'm going to convert this to a Github discussion so that we can gain some consensus on the implementation before committing to a feature ticket.
