### ISSUE TITLE
PuppetDB Node Graph Visualizer

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#627]
**As a** user

**I would like to** query PuppetDB for a specific node and have it return a node graph visualization similar to the Puppet Manifest Node Graph feature.

**so that I** don't miss having this feature in the Puppet Console web interface

**Comment by Sharpie** [comment]
I think we should look into what TensorBoard does:

https://www.tensorflow.org/tensorboard/graphs

The graph of a machine learning model can be a huge, dense, dataset with thousands of nodes and nested computations (i.e classes or defined types) and they’ve done a lot of work to make dagre-d3 display it in a way that is performant and sane to navigate.

**Comment by glennsarti** [comment]
Heya @Sharpie !!

Interestingly, James ported the visualizer to use Cytoscape (https://js.cytoscape.org/) which is (claimed by Cyto) actually used by tensorflow!
