### ISSUE TITLE
Review Bolt Commands

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#639]
The current Bolt Commands do not work well with latest Bolt, as paths have changed or de-prioritized compared to project level files. 

https://github.com/puppetlabs/puppet-vscode/blob/d655924dd4a00dbfe0392dce9721889822b5c285/src/feature/BoltFeature.ts#L11-L12

https://github.com/puppetlabs/puppet-vscode/blob/d655924dd4a00dbfe0392dce9721889822b5c285/src/feature/BoltFeature.ts#L27-L28

Additionally, telemetry shows low usage compared to other parts of the extension.

This ticket should evaluate whether to change these paths to project level paths or remove them as not helpful/needed

**Comment by glennsarti** [comment]
If it hasn't been invoked in the last 30 days, +1 to deprecate.  Easy enough to re-add

**Comment by jpogran** [comment]
There is still some minimal use, but that may be from a scenario where a user tries the command and finds it not working because of paths and then never tries again, when they would have used it if it had the correct paths.

I vote for removing them from the activation event list, adding a deprecation warning message in `0.27.0` with a link to this issue for feedback, then remove in `0.28.0` if no one responds.
