### ISSUE TITLE
Review Bolt snippets

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#640]
We ship two 'complete' snippets for Bolt inventory and Bolt config yaml files, along with four smaller snippets for groups, nodes and transports. We have no telemetry on usage of these features since they are snippets, but some users have reported limited usefullness of them. One user has reported that they show up in non Bolt files, so if we keep them, we need to restrict the scope when they activate.

This ticket should get some user opinions on the snippets and decide whether to keep them or not.

https://github.com/puppetlabs/puppet-vscode/blob/d655924dd4a00dbfe0392dce9721889822b5c285/snippets/bolt.snippets.json#L2-L4

https://github.com/puppetlabs/puppet-vscode/blob/d655924dd4a00dbfe0392dce9721889822b5c285/snippets/bolt.snippets.json#L14-L16

https://github.com/puppetlabs/puppet-vscode/blob/d655924dd4a00dbfe0392dce9721889822b5c285/snippets/bolt.snippets.json#L32-L65

**Comment by glennsarti** [comment]
Ping @jpogran Should this be excluded from being stale?

**Comment by jpogran** [comment]
Thanks. Marked to keep.
