### ISSUE TITLE
Configure prettier

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#643]
Prettier is defined in `settings.json` but isn't installed in the `devDependencies` so it's not used by default.

Without a style enforcement, the code has several different styles implemented. Adding a standard will keep code style consistent and reduce effort for someone new to contribute to the project.

- [ ] Add prettier to dependencies
- [ ] Create `.prettierrc` and set with sane defaults
- [ ] Ensure that it is configured to work with eslint in #642 
- [ ] Lint and commit fixes

**Comment by glennsarti** [comment]
- [ ] Modify project settings to use prettier as the Document Formatter instead of the default JavaScript formatter.
