### ISSUE TITLE
Move gifs stored in docs/assests

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-vscode#646]
The gifs stored in docs/assets are currently used in the puppet-vscode.github.io site and do not make sense to be stored here. Additionally the README.md file has one or two links to these, which doesn't make sense for a marketplace extension. We should keep these doc-type gifs in the lingua-pupuli/docs repo and make something specific for the README.

**Comment by glennsarti** [comment]
+1 The should've been removed as part of cleaning up the README.md to the new website.
