### ISSUE TITLE
server crashes when workspace path has non-standard characters

### ISSUE THREAD

**Issue by bp85** [puppetlabs/puppet-vscode#663]
### What Versions are you running?

OS Version: OSX 10.15.3
VSCode Version: 1.45.1
Puppet Extension Version: 0.26.1
PDK Version: 1.18.0

### What You Are Seeing?
 syntax error near unexpected token `('
[Info  - 9:30:53 PM] Connection to server got closed. Server will restart.
### What is Expected?
server will start normally.

Forgive me if I'm mistaken, but I think it's a simple fix by just adding quotes around the value of workspace.

### How Did You Get This To Happen? (Steps to Reproduce)
1. create a directory with spaces or special characters
2. add the directory to workspace
3. add some puppet code in workspace

### Output Log
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/ruby /Users/user1/.vscode/extensions/puppet.puppet-vscode-0.26.1/vendor/languageserver/puppet-languageserver --stdio --timeout=10 --local-workspace=/Users/user1 (test)/proj1--puppet-version=4.8.2'
[Info  - 9:30:53 PM] Connection to server got closed. Server will restart.
[Error - 9:30:53 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by glennsarti** [comment]
@jpogran Looks like a simple quoting problem.

**Comment by jpogran** [comment]
Thanks @bp85 for the report, we'll get this addressed for the 0.27 release

**Comment by bp85** [comment]
Appreciate the quick response @jpogran.

**Comment by jpogran** [comment]
No problem @bp85 , thanks for the bug report!
