### ISSUE TITLE
puppet open node has include error

### ISSUE THREAD

**Issue by hcps-admin** [puppetlabs/puppet-vscode#667]
Getting "There were no resources created in the node graph.  Is there an include statement missing?

**Comment by jpogran** [comment]
@hcps-admin Can you fill out any of the information asked in the issue template?

**Comment by hcps-admin** [comment]
issue template?

**Comment by hcps-admin** [comment]
### What Versions are you running?

OS Version: Windows 10
VSCode Version: 1.45.1
Puppet Extension Version: 0.26.1
PDK Version: 1.17.0

### What You Are Seeing?

### What is Expected?
Display the graph of dependencies like the doc shows

### How Did You Get This To Happen? (Steps to Reproduce)
view, command pallet, puppet open node
Then in bottom right corner, I get: There were no resources created in the node graph. Is there an include statement missing?

**Comment by jpogran** [comment]
The `Puppet Node Graph` feature can't compile manifests that have classes in them without them being 'included' inside the manifest. For example:

```
class foo {
  # class content
}

include foo
```
