### ISSUE TITLE
Cannot register configuration defaults for 'files.associations'. Only defaults for language specific settings are supported.

### ISSUE THREAD

**Issue by ThiefMaster** [puppetlabs/puppet-vscode#678]
I'm getting this error message during startup. Everything seems to work fine, but the message is annoying (especially since I'm on Insiders and thus restart vscode about once a day to update):

> [puppet.puppet-vscode]: Cannot register configuration defaults for 'files.associations'. Only defaults for language specific settings are supported.

### What Versions are you running?

OS Version: Win 10
VSCode Version: 1.46.0-insider
Puppet Extension Version: 0.27.0
PDK Version: n/a

**Comment by jpogran** [comment]
Thanks for reporting this. This is my bad, in the early days of VS Code they allowed you to set a 'default configuration' that would put users in a good position out of the gate. At some point, they restricted this to settings that only apply to this extension, not the entire product. It wasn't throwing errors on stable, but haven't tried insiders in awhile so I missed it throwing an error.

This is an easy fix, I'll get a point release out as soon as I can
