### ISSUE TITLE
Submit extension also in Open VSX store

### ISSUE THREAD

**Issue by bittner** [puppetlabs/puppet-vscode#690]
**Is your feature request related to a problem? Please describe.**
Can you submit your extension also in the Open VSX store, please? That would help a lot!

This is a new store for use with VSCodium, to escape the issues related to Microsoft's licensing.

**Describe the solution you'd like**
This extension should be available from https://open-vsx.org/?search=puppet

**Additional context**
More infos: https://github.com/VSCodium/vscodium/pull/404

**Comment by jpogran** [comment]
Thanks for letting us know about openvsx, I was not aware of it. I'll work on figuring out how to accomplish this

**Comment by glennsarti** [comment]
Should note that we do use Telemetry in this extension.

**Comment by mhutter** [comment]
Here's the documentation on [how to publish to VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by heylix** [comment]
>Should note that we do use Telemetry in this extension.

Can you make that opt-in? Which **valuable** information did you gather from said Telemetry already? You may be able to assess how many people use vscodium and if it's worth publishing.

**Comment by jpogran** [comment]
Hi @bittner, @mhutter, @heylix, thank you for the discussion about the Open VSX store. I'm going to move this issue to the discussions page where we can iron out a few things and then create a an issue to publish this extension to that gallery. We want to start supporting VSCodium and Gitpod, but have a few questions about licensing.
