### ISSUE TITLE
правка

### ISSUE THREAD

**Issue by AstraLrus** [puppetlabs/puppet-vscode#701]
**Summary of the new feature**

A clear and concise description of what the problem is that the new feature would solve.

For example:

---
**As a** user

**I would like to** automatically format my puppet manifests

**so that I** don't have to remember to do it myself.

**Comment by glennsarti** [comment]
Hi @AstraLrus ,

VScode can already do this for you.  We have an example of Format-On-Save in our documentation 

https://puppet-vscode.github.io/docs/features/formatting/#format-on-save
