### ISSUE TITLE
Language server stops responding after notifying about trailing white space on puppet v4.x (not 5-6.x)

### ISSUE THREAD

**Issue by mike-onehub** [puppetlabs/puppet-vscode#714]
### What Versions are you running?

OS Version: MacOS 10.15.7
VSCode Version: 1.50.1
Puppet Extension Version: 0.28.0
PDK Version: 1.18.1.0-1.osx10.15

### What You Are Seeing?
Code completion seems to stop responding a few seconds (10-15?) after a warning for trailing white space is raised.
This can be at the end of a line or on a blank line. This seems to only happen with 4.x puppet dsl set. Versions 5-6.x don't seem to be affected.
When typing a reserved word on a new line immediately after said trailing whitespace (exec in my examples), the first indicator is the colorizer no longer works, characters are grey and the completion dialog doesn't appear. When hovering mouse over a reserved word (again 'exec' as example), the popup only displays 'Loading...'
Reloading the LServer/Editor by reselecting the puppet lang version helps only for about 30 seconds before the same starts happening again.

### What is Expected?
Code is colorized and completion should work.
Hovering mouse over reserved words should correctly query LServer and return relevant info.

### How Did You Get This To Happen? (Steps to Reproduce)
Open a new or existing .pp file.
Start a new line with adding a class {} with a resource in it (exec{} for example}. Doesn't matter if you give it a title or not.
Put 1-2 trailing white spaces after the closing } on the resource.
Go to the next line, maybe wait 10 seconds before typing.
Type in a new resource (exec...) and notice colors are no longer being applied.
Remove your last line of edits and the previous trailing white spaces.
Save file.
Notice the console and editor spaces do not update and revert to former status.

```
# Install the certbot-haproxy plugin and certbot
class profiles::certbot_haproxy {
  # Setup the certbot user
  group {'certbot_group':
    ensure  =>  present,
    before  =>  User['certbot_user'],
    name    =>  'certbot',
    members =>  'certbot,haproxy',
  }
  user {'certbot_user':
    ensure  =>  present,
    require =>  Group['certbot_group'],
    name    => 'certbot',
    comment =>  'Certbot user',
    gid     =>  'certbot',
    groups  =>  'haproxy',
    home    =>  '/opt/certbot',
    shell   =>  '/bin/bash',
  }
  file {'certbot_homedir':
    ensure  =>  directory,
    require =>  User['certbot_user'],
    path    =>  '/opt/certbot',
    owner   =>  'certbot',
    group   =>  'certbot',
    mode    =>  '0664',
  }
  file {'cerbot_logs':
    ensure  =>  directory,
    require =>  File['certbot_homedir'],
    path    =>  '/opt/certbot/logs',
    owner   => 'certbot',
    group   => 'certbot',
    mode    =>  '0664',
  }
  file {'cerbot_config':
    ensure  =>  directory,
    require =>  File['certbot_homedir'],
    path    =>  '/opt/certbot/config',
    owner   => 'certbot',
    group   => 'certbot',
    mode    =>  '0664',
  }
  file {'cerbot_letsencryptconfig':
    ensure  =>  directory,
    require =>  File['certbot_homedir'],
    path    =>  '/opt/certbot/.config/letsencrypt',
    owner   => 'certbot',
    group   => 'certbot',
    mode    =>  '0664',
  }
  file {'certbot_haproxy_sudo':
    ensure  =>  present,
    require =>  User['certbot_user'],
    path    =>  '/etc/sudoers.d/certbot-haproxy-sudo.conf',
    owner   =>  'root',
    group   =>  'root',
    mode    =>  '0640',
    source  =>  'puppet:///modules/profiles/certbot-haproxy-sudo.conf',
  }
  file  {'certbot_cli_ini':
    ensure  =>  present,
    require =>  File['certbot_letsencryptconfig'],
    path    =>  '/opt/certbot/.config/letsencrypt/cli.ini',
    owner   =>  'certbot',
    group   =>  'certbot',
    mode    =>  '0640',
    source  =>  'puppet:///modules/profiles/cli.ini',
  }

  # Install certbot_haproxy plugin and certbot

  # Pull down the plugin only if we can't find the file already
  $version = 'v0.2.0'
  $url = "https://github.com/onehub/certbot-haproxy/archive/${version}.tar.gz"
  exec {'wget_certbot_haproxy':
    path    =>  ['/usr/bin','/usr/sbin'],
    command =>  "/usr/bin/wget -q -P /root/ ${url} -O certbot-haproxy-${version}.tgz",
    creates =>  "/root/certbot-haproxy-${version}.tgz",
    returns =>  '0',
    timeout =>  '15',
    tries   =>  '2',
    unless  => "find /root/ -name certbot-haproxy-${version}.tgz -type f"
  }
  exec { 'untar_certbot_haproxy':
    path    =>  ['/usr/bin','/usr/sbin'],
    onlyif  => "find /root/ -name certbot-haproxy-${version}.tgz -type f",
    command => "/usr/bin/tar -xzf certbot-haproxy-${version}.tgz",
    creates => '/root/certbot-haproxy-0.2.0/setup.py',
  }
  exec {'testing':}
  exec 
  #
```
}

### Output Log
Attached
[PuppetLServer202010220241pm.log](https://github.com/puppetlabs/puppet-vscode/files/5426058/PuppetLServer202010220241pm.log)
![by default 2020-10-22 at 1 01 49 PM](https://user-images.githubusercontent.com/68404384/96933593-95176680-1475-11eb-8384-7720fd3250e9.png)
![by default 2020-10-22 at 1 05 53 PM](https://user-images.githubusercontent.com/68404384/96933601-98125700-1475-11eb-8e17-177c0d64e18a.png)

Please note that after I turned on logging following the instructions below, I couldn't reproduce the issue.
The issue returned once I turned off logging and returned it back to previous settings.
I attached the log regardless just because it may be helpful.
I've attached two screenshots showing the issues.

**Comment by jpogran** [comment]
Thank you for the detailed report @mike-onehub, unfortunately I am going to disappoint you. The key part of your report is that this is happening on Puppet 4 and not 5 or 6. In our experience Puppet 4 has had some issues with dealing with/parsing incomplete manifests as we type in the editor. We have been moving off Puppet 4 for some time now as it is EOL and have been moving the extension internals to use the newer language constructs introduced in 5 and 6. As of 1.0.0 we will be dropping support for Puppet 4 in sync with the rest of the Puppet community.

Please reply back if this issue appears with Puppet 5 or 6 versions.

**Comment by mike-onehub** [comment]
Thank you for the information. It's a good thing that I am planning on
skipping 4 when I migrate this environment from 3. I was thinking of going
to 5. Which would you recommend?
