### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by kyle-edwards** [puppetlabs/puppet-vscode#716]
The link for the Windows Puppet Agent (https://docs.puppet.com/puppet/latest/install_windows.html) on the "Prerequisites" page (https://puppet-vscode.github.io/docs/getting-started/#prerequisites) is broken. It goes to a 404 page.

**Comment by jpogran** [comment]
Thanks for the report @kyle-edwards! Apologies for the delay in response, the month of Puppetize is always a busy one. I'm going to copy this issue over to our docs repo and get it taken care over

**Comment by jpogran** [comment]
Closing this in favor of the one open in the docs repo
