### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sebasvalencia726** [puppetlabs/puppet-vscode#718]
- Issue Type: `Performance`
- Extension Name: `puppet-vscode`
- Extension Version: `1.0.0`
- OS Version: `Linux x64 5.4.0-56-generic`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/puppet.puppet-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sebasvalencia726** [comment]
[puppet.puppet-vscode-unresponsive.cpuprofile.txt](https://github.com/puppetlabs/puppet-vscode/files/5676059/puppet.puppet-vscode-unresponsive.cpuprofile.txt)

**Comment by sebasvalencia726** [comment]
thank you

**Comment by jpogran** [comment]
Thank you @sebasvalencia726 for the detailed issue! I appreciate you went to the lengths of getting a cpuprofile recorded for this.

Can you also describe what you were doing at the point of high cpu usage? Did you have open a single Puppet module? Or a Puppet Control Repo? Were you using any of the features at the time (like formatting documents or running commands)?

I would appreciate it if you could do one more step for me. Could you follow the directions for `Reporting a Problem` on this page https://puppet-vscode.github.io/docs/experience-a-problem? Having the debug logs as well as the cpuprofile could help link the two.
