### ISSUE TITLE
Puppet versions below 5.0 are not supported by the language server

### ISSUE THREAD

**Issue by harry-xm** [puppetlabs/puppet-vscode#729]
### What Versions are you running?

OS Version: macOS 11
VSCode Version: 1.53.2
Puppet Extension Version: 1.1.0
PDK Version: 1.18.1.0

### What You Are Seeing?
Puppet versions below 5.0 are not supported by the language server.

### What is Expected?
Hide unsupported Puppet versions in the menu.
### How Did You Get This To Happen? (Steps to Reproduce)
1. Switch to Puppet 4.7.1 from the status bar button.

### Output Log
```
/Users/x/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/lib/puppet_languageserver.rb:219:in `init_puppet': Detected Puppet 4.7.1 however the Language Server requires Puppet 5.0 and above (RuntimeError)
	from /Users/x/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info] Connection to server got closed. Server will restart.
```

**Comment by glennsarti** [comment]
Ahh @lin-xiaomi  Yes! good point. we can fix that

**Comment by jpogran** [comment]
I'm pushing this off to the 1.3.0 release because PDK 2.0 has removed 4.X from distributions, so this has lesser priority

**Comment by jpogran** [comment]
The extension pulls a list of Puppet versions from the currently install PDK or Puppet Agent. This may not line up with what the extension supports.

To fix this, the method that pulls the list of versions has to filter based on 6 and above and only present the ones that are supported for the user to choose in the version selector.
