### ISSUE TITLE
Node Graph: "There are no resources created ..." error message

### ISSUE THREAD

**Issue by rajeshr264** [puppetlabs/puppet-vscode#734]
## Describe the Bug
When I selected "Puppet Node Graph" in VS Code on my clone of https://github.com/puppetlabs/puppetlabs-ntp/blob/main/manifests/service.pp, I get this error message: 

"There were no resources created in the node graph. Is there an include statement missing?"

## Expected Behavior
I expect to see resources being recognized and a node graph of the resources drawn.

## Steps to Reproduce
1. clone of https://github.com/puppetlabs/puppetlabs-ntp/blob/main/manifests/service.pp
2. Open VS Code and open the Node Graph 
3. You will see the error message
4. Try another file: I have tried another file : https://github.com/RARYates/ourapp/blob/master/manifests/init.pp and you will get the same error.

## Environment
 -  VS Code 1.54.3
 - Platform : Windows 10
 - pdk 2.0.0.0
 - Ruby 2.5.8
 - Puppet 6.17.0
 -

**Comment by jpogran** [comment]
@rajeshr264 The (admittingly minimal) error message is pointing you to the problem. Both of the example files don't `include` the class you're trying to graph. You will need to add a temporary `include <NAME>` in the manifest, then run `Open Node Graph` for it to parse successfully.

**Comment by binford2k** [comment]
@rajeshr264 think about it this way. If you wrote a bash script like this, what would it do when you ran it?

``` bash
#! /bin/bash

function do_a_thing {
    echo "did a thing"
}
```

It would do nothing, because it just defines a function and never invokes it. Same thing with a Puppet class. Unless you declare it, it doesn't add anything to the catalog.
