### ISSUE TITLE
Icon issue since 1.2.0

### ISSUE THREAD

**Issue by yakirgb** [puppetlabs/puppet-vscode#741]
### What Versions are you running?

OS Version: OSX Big Sur
VSCode Version: 1.56.0 (insiders)
Puppet Extension Version: 1.2.0
PDK Version: 2.1.0

### What You Are Seeing?
The icon on right-top screen looks huge
### What is Expected?
smaller size of icon

Example:
![image](https://user-images.githubusercontent.com/12082308/114309672-a5d59a80-9af0-11eb-8b90-c4b87df1262f.png)

**Comment by jpogran** [comment]
@yakirgb Can you please verify your version of the Puppet Extension? We just released 1.2.0...so there isn't a 1.6.0.

**Comment by yakirgb** [comment]
Right, changed, using 1.2.0

**Comment by yakirgb** [comment]
How it looks right now:
![image](https://user-images.githubusercontent.com/12082308/114540180-e56dc500-9c5d-11eb-83f5-224ec4b4fdca.png)

**Comment by jpogran** [comment]
Missed that you were using an Insiders VS Code build. VS Code 1.55.1 is the latest stable released and the icon appears normally there. The icon displays differently in 1.56 Insiders release, so something changed in the preview version. Will look through changelog to see if this is intentional or a bug in vs code.

**Comment by da-ar** [comment]
![toolbar-icons](https://user-images.githubusercontent.com/1346683/114572645-9466cc80-9c6f-11eb-8526-42f977ef5d36.gif)

Comparision between release 1.55 (top) and 1.56-insiders (bottom) builds on Big Sur

**Comment by jpogran** [comment]
This appears to have been resolved in the latest stable build. Closing this out for now, please reopen if this reoccurs

![image](https://user-images.githubusercontent.com/272569/121241855-e4c26b00-c869-11eb-95c3-7de246761e85.png)
