### ISSUE TITLE
Add configuration for puppet-lint

### ISSUE THREAD

**Issue by dhs-rec** [puppetlabs/puppet-vscode#764]
**Summary of the new feature**
**As a** user
**I would like to** be able to configure `puppet-lint`
**so that I** can customize which problems are shown in the editor

**Comment by jpogran** [comment]
Hi @dhs-rec, thanks for the request. You can customize which problems are shown by using the built-in methods to configure puppet-lint. There is a [configuration file](https://github.com/rodjek/puppet-lint#configuration-file), and the VS Code Puppet Extension will pick up the settings to use from there.

**Comment by dhs-rec** [comment]
OK, thanks. Just one more question: What does "local" mean in this context? We have a Git repository which contains multiple Puppet modules. Would I need to put a .puppet-lint.rc file into every module or would it be sufficient to put it into the repository root?

**Comment by sanfrancrisko** [comment]
Hi @dhs-rec , in the scenario you are in, with multiple modules in one repository, you only need to have a single `puppet-lint.rc`, either in:

- `/etc/puppet-lint.rc`
- `~/.puppet-lint.rc`

This will apply the config to all modules opened in the editor

**Comment by sanfrancrisko** [comment]
Hopefully you've been able to configure `puppet-lint` as described above? If not, please come back on the ticket and we can discuss further. Closing the issue for now.
