### ISSUE TITLE
treesitter config for Puppet language

### ISSUE THREAD

**Issue by lcrownover** [puppetlabs/puppet-vscode#766]
I would like to try and get the ball rolling on a [treesitter](https://tree-sitter.github.io/tree-sitter/) config for the Puppet language. 

Using [neovim 0.5+](https://github.com/neovim/neovim) and [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), we can now hook into the [puppet-editor-services](https://github.com/puppetlabs/puppet-editor-services) language server, but we're still missing language parsing without the [vim-puppet](https://github.com/rodjek/vim-puppet) plugin. 

I know this isn't directly related to VS Code, but I was encouraged to post here per the following response from our support representative:

> We don't have any immediate plans for implementing a treesitter for the puppet language, we're focusing on the PDK at the moment. But to get the ball rolling, you can ask them to create an issue in https://github.com/puppetlabs/puppet-vscode and we'll route it to the correct repo

Thanks!

**Comment by chelnak** [comment]
@lcrownover Is this something that you are still interested in?

I think it would be a great addition to editor-services.
