### ISSUE TITLE
ruby: error while loading shared libraries

### ISSUE THREAD

**Issue by 5n00p4eg** [puppetlabs/puppet-vscode#805]
### What Versions are you running?

OS Version: Fedora 35 (Linux x64 5.15.16-200.fc35.x86_64)
VSCode Version: VSCodium Version: 1.63.2
Puppet Extension Version: 1.4.0
PDK Version: pdk-2.3.0.0-1.fc34.src.rpm

### What You Are Seeing?
When I opening any .pp file, I see that server wasn't started.

### What is Expected?
Server is started.

### How Did You Get This To Happen? (Steps to Reproduce)

I simply installed PDK using official way from documentation and then installed vscode extension.
I also checked that libxcrypt & libxcrypt-compat is installed, and actual libs are present in my system.

### Output Log

DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkNewModule command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkValidate command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkTestUnit command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkNewClass command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkNewTask command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkNewDefinedType command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkNewFact command
DEBUG: 2022-02-03T12:24:13.985Z Registered extension.pdkNewFunction command
DEBUG: 2022-02-03T12:24:13.985Z Found a valid Puppet installation at /opt/puppetlabs/pdk/puppet
DEBUG: 2022-02-03T12:24:14.011Z Setting status bar to Initializing
DEBUG: 2022-02-03T12:24:14.011Z Configuring language client options
DEBUG: 2022-02-03T12:24:14.011Z Creating server options
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable DEVKIT_BASEDIR=/opt/puppetlabs/pdk
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable GEM_HOME=/opt/puppetlabs/pdk/share/cache/ruby/2.7.0
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable GEM_PATH=/opt/puppetlabs/pdk/private/ruby/2.7.3/lib/ruby/gems/2.7.0:/opt/puppetlabs/pdk/share/cache/ruby/2.7.0:/opt/puppetlabs/pdk/private/puppet/ruby/2.7.0
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable RUBY_DIR=/opt/puppetlabs/pdk/private/ruby/2.7.3
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable RUBYLIB=/opt/puppetlabs/pdk/lib:
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable PATH=/opt/puppetlabs/pdk/bin:/opt/puppetlabs/pdk/private/ruby/2.7.3/bin:/opt/puppetlabs/pdk/private/git/mingw64/bin:/opt/puppetlabs/pdk/private/git/mingw64/libexec/git-core:/opt/puppetlabs/pdk/private/git/usr/bin:/app/bin:/usr/bin:/home/user/.var/app/com.vscodium.codium/data/node/bin:/home/user/.var/app/com.vscodium.codium/data/cargo/bin:/home/user/.var/app/com.vscodium.codium/data/python/bin
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Using environment variable RUBYOPT=rubygems
DEBUG: 2022-02-03T12:24:14.013Z [getRubyEnvFromPDK] Editor Services will invoke with: /opt/puppetlabs/pdk/private/ruby/2.7.3/bin/ruby /home/dboiko/.var/app/com.vscodium.codium/data/codium/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/puppet-languageserver --stdio --timeout=10 --local-workspace='/secret_path_____' --debug=/home/user/vs-puppet-logs
DEBUG: 2022-02-03T12:24:14.013Z Creating language client
DEBUG: 2022-02-03T12:24:14.021Z Setting status bar to Initialization Complete
DEBUG: 2022-02-03T12:24:14.022Z Configuring Local::stdio connection handler
DEBUG: 2022-02-03T12:24:14.022Z Setting status bar to Starting languageserver
DEBUG: 2022-02-03T12:24:14.023Z Registered Format Document provider
DEBUG: 2022-02-03T12:24:14.024Z Registered command for node graph event handler
DEBUG: 2022-02-03T12:24:14.024Z Registered onDidSaveTextDocument for node graph event handler
DEBUG: 2022-02-03T12:24:14.024Z Registered DebugAdapterDescriptorFactory for Puppet
DEBUG: 2022-02-03T12:24:14.024Z Registered DebugConfigurationProvider for Puppet
/opt/puppetlabs/pdk/private/ruby/2.7.3/bin/ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
[Info  - 2:24:14 PM] Connection to server got closed. Server will restart.
/opt/puppetlabs/pdk/private/ruby/2.7.3/bin/ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
[Info  - 2:24:14 PM] Connection to server got closed. Server will restart.
/opt/puppetlabs/pdk/private/ruby/2.7.3/bin/ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
[Info  - 2:24:14 PM] Connection to server got closed. Server will restart.
/opt/puppetlabs/pdk/private/ruby/2.7.3/bin/ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
[Info  - 2:24:14 PM] Connection to server got closed. Server will restart.
/opt/puppetlabs/pdk/private/ruby/2.7.3/bin/ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
[Error - 2:24:14 PM] Connection to server got closed. Server will not be restarted.
DEBUG: 2022-02-03T12:24:15.135Z pdk shell started, pid: 219

**Comment by 5n00p4eg** [comment]
I think it's related to vscodium install method, it was a Flatpack package. With the native one, it works fine.

**Comment by jordanbreen28** [comment]
Closing inline with above comment
