### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by claviola** [puppetlabs/puppet-vscode#834]
I see that #819 #825 were finally fixed by #833. Thanks a lot for that! But the current version was released over 18 months ago. Is there a plan to cut a release that would feature this fix?

**Comment by davidsandilands** [comment]
@claviola hello sorry for a much delayed response we are in the process of planning our commitments for q3 and q4 and I will update here and the Puppet slack community to confirm more details

**Comment by jc16180** [comment]
Please, please can we have an update on this. :(

**Comment by ELLIOTTCABLE** [comment]
Ah, I was wondering if I was seeing a _new_ bug — didn't realize the fix to #819 had never shipped. )=

**Comment by davidsandilands** [comment]
@jc16180 @ELLIOTTCABLE I want to confirm this has been commited for Q4 and I will update as a release date becomes clearer

**Comment by jordanbreen28** [comment]
v1.4.2 of puppet-vscode was shipped this morning!
